---
_hotel_id: PLA713
_portal_id: ''
latitude: 25.28722
longitude: 51.54395
name: Plaza Inn Doha
email: ''
phone_number: "--"
address:
  street1: Al Meena Street
  street2: ''
  state: ''
  city: Doha
  country: 
  zip_code: ''
